### PR TITLE
Add hltespr (sprint note 3) to device database

### PR DESCRIPTION
**Pull request by MattMatt0240**

### CODE REVIEW

**Comment by JustArchi** [comment]
:+1:

**Comment by MattMatt0240** [comment]
I will also add sprint tab 3 LTE later, just a few devices I have on my end ;)

I was also thinking, can a GUI be implemented via java?

**Comment by JustArchi** [comment]
Nope, it's SH script. I mean you could add GUI wrapper that would translate commands and STDIN/STDOUT but it seems like pointless thing. Tool is supposed to work and make a final effect that works for you, not look pretty with buttons like "click here for root"

**Comment by MattMatt0240** [comment]
Gotcha, thanks for clarifying. Looking forward to improvements!

**Pull request merged**
